### ISSUE TITLE
Enhancement - Dependant files from galley

### ISSUE THREAD

**Issue by liladude** [biblhertz/jats_to_ojs#1]
Some galleys, like html, might need dependant files (i.e. images) that should be associated with the image. 
I have managed to manually combine the file that I added as a galley on publink as the dependant file on the XML galley. Compare 
- downloaded native https://keeper.mpdl.mpg.de/f/db54c83d53d649cfb861/
-  uploaded native https://keeper.mpdl.mpg.de/f/92a9c5df29564feca797/

**Comment by hawkenbury** [comment]
I have enabled an option for dependent files - please check it

**Comment by hawkenbury** [comment]
Just looking at it again - it looks like the link between the two files is made through the file name field which is now included
