### ISSUE TITLE
Bug - missing orcid in OJS file and accents in author name

### ISSUE THREAD

**Issue by liladude** [biblhertz/jats_to_ojs#2]
The generated OJS file is missing the orcid number and accents are removed
Original JATS https://keeper.mpdl.mpg.de/smart-link/337e03f2-c9e7-4bc1-8f83-aa60d6859678/
PubLink Ojs export https://keeper.mpdl.mpg.de/smart-link/95ce5d89-0031-4f8f-bcf2-bda8a6c147dc/
Corrected native import https://keeper.mpdl.mpg.de/smart-link/6e49c225-95eb-4f68-a295-d65a398b4f77/

**Comment by hawkenbury** [comment]
Orcid number should work now - https://publink.biblhertz.it
Special characters is a problem because XML is plain text, some of these characters are not represented.
When the bib file is imported special characters are removed to stop problems

**Comment by liladude** [comment]
Tested export from https://publink.biblhertz.it/, no ORCID

**Comment by hawkenbury** [comment]
orcid included in OJS output as well as in JATS output
special characters create a problem with ascii text format so are removed from text input, more research needed to correct this
