### ISSUE TITLE
Enhancement - File genre and Galley name need to be editable

### ISSUE THREAD

**Issue by liladude** [biblhertz/jats_to_ojs#3]
"genre" field in files need to be edited. I have a list, but every journal might have their own, so it could be a general setting where you create your list and you set the one needed. Same for the Galley name since you cannot guess how the platform call each galley.

**Comment by hawkenbury** [comment]
Which file type has genre setting? Do you mean in OJS?

**Comment by liladude** [comment]
no, the genre is inside the Native XML

**Comment by hawkenbury** [comment]
genre setting now enabled in galley file upload

**Comment by hawkenbury** [comment]
latest version has this enabled
