### ISSUE TITLE
Bug: multiparagraph abstract is ignored

### ISSUE THREAD

**Issue by liladude** [biblhertz/jats_to_ojs#7]
When creating the Native XML file, only the first paragraph of abstracts is inserted. Subsequent abstract paragraphs are ignored.

**Comment by hawkenbury** [comment]
I have corrected this - paragraph tags may be lost in abstract

**Comment by hawkenbury** [comment]
multi paragraph abstracts should work now
Abstracts given a separate tab in the interface and a separate editor for each paragraph encountered
