### ISSUE TITLE
BUG: error on OJS output (FATAL)

### ISSUE THREAD

**Issue by liladude** [biblhertz/jats_to_ojs#9]
`Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, Biblhertz\Article\om\AAbstract given in /var/www/src/article/src/adapters/OMToOJSArticleAdapter.php:284 Stack trace: #0 /var/www/src/article/src/adapters/OMToOJSArticleAdapter.php(284): str_replace('"', '\xE2\x80\x9D', Object(Biblhertz\Article\om\AAbstract)) #1 /var/www/src/article/src/adapters/OMToOJSArticleAdapter.php(240): Biblhertz\Article\Adapters\OMToOJSArticleAdapter->writePublicationMetadata() #2 /var/www/src/article/src/adapters/OMToOJSArticleAdapter.php(176): Biblhertz\Article\Adapters\OMToOJSArticleAdapter->writePublication() #3 /var/www/src/article/src/adapters/OMToOJSArticleAdapter.php(60): Biblhertz\Article\Adapters\OMToOJSArticleAdapter->writeArticle() #4 /var/www/html/article.html(154): Biblhertz\Article\Adapters\OMToOJSArticleAdapter->generateXML() #5 {main} thrown in /var/www/src/article/src/adapters/OMToOJSArticleAdapter.php on line 284`

**Comment by hawkenbury** [comment]
resolved
